import { CallProvider } from "@/provider/SoketProvider";
import "./globals.css";
import GlobalProvider from "@/provider/GlobalInit";
import CallPopup from "@/components/CallPopUp/CallPopUp";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <GlobalProvider>
          <CallProvider>
            {children}
            <CallPopup />
          </CallProvider>
        </GlobalProvider>
      </body>
    </html>
  );
}
